# Generated by Django 5.2 on 2025-04-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('address', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
